import {strict as assert} from 'node:assert';
import {SOURCES,articles,matchNews,dedupeNews,playProbability,projectionMean,officialInjuries} from './player-intel-lib.mjs';
assert.equal(SOURCES.length,30);assert.equal(new Set(SOURCES.map(s=>s.id)).size,30);
const rss='<rss><item><title><![CDATA[Drake Maye &amp; Patriots practice report]]></title><link>https://example.com/maye</link><pubDate>Tue, 06 Oct 2026 14:00:00 GMT</pubDate></item></rss>';
const rows=articles(rss,'https://example.com');assert.equal(rows[0].title,'Drake Maye & Patriots practice report');
assert.equal(articles('<feed><entry><title>Drake Maye update</title><link href="https://example.com/new"/><updated>2026-10-06T14:00:00Z</updated></entry></feed>','https://example.com')[0].url,'https://example.com/new');
assert.equal(matchNews(rows,[{name:'Drake Maye',key:'maye'}],SOURCES[0],Date.parse('2026-10-07')).length,1);
assert.equal(matchNews(rows,[{name:'Drake Maye',key:'maye'}],SOURCES[0],Date.parse('2026-11-07')).length,0);
assert.equal(dedupeNews([{player_key:'x',title:'Same story',source:'a'},{player_key:'x',title:'Same story',source:'b'}]).length,1);
assert.equal(playProbability({status:'Questionable'}),null);
assert.equal(playProbability({injury_risk:50}),null);
assert.equal(playProbability({play_probability:.73}),73);
assert.equal(playProbability({play_probability:130}),null);
const source=(source,value,week=5,scoring='PPR')=>({source,value,week,scoring,season:2026});
const average=projectionMean([source('a',10),source('b',20),source('c',60),source('missing',null),source('old',99,4),source('std',99,5,'STD'),source('a',50)],2026,5,'PPR');
assert.equal(average.value,30);assert.equal(average.count,3);
const html='<title>2026 NFL Week 5 Injury Report</title><tr><td>Drake Maye</td><td>QB</td><td>Shoulder</td><td>Limited Participation</td><td>Questionable</td></tr>';
const players=[{name:'Drake Maye',key:'maye'}];
assert.equal(officialInjuries(html,2026,4,players,'https://nfl.com').length,0);
assert.equal(officialInjuries(html,2026,5,players,'https://nfl.com')[0].play_probability,null);
assert.equal(officialInjuries(html.replace('Questionable','Out'),2026,5,players,'https://nfl.com')[0].play_probability,0);
console.log('Passed: 30 distinct sources, XML headlines, dates, deduplication, honest injury probabilities, same-week same-format arithmetic means, and verified report weeks.');
