(()=>{
const SB_URL='https://nphrdqabpyaabsrahkja.supabase.co';
const SB_KEY='sb_publishable_C4Mt1TF85R7piT2YhGQlSQ_NTsrhL8K';
const TEAM_ID='11111111-1111-4111-8111-111111111111';
let sb,user,membership,liveGame;
const $=s=>document.querySelector(s);
const esc2=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function injectCss(){const s=document.createElement('style');s.textContent=`#liveGate{position:fixed;inset:0;z-index:9999;background:radial-gradient(circle at 50% 0,#0b3155,#020812 70%);display:grid;place-items:center;padding:18px;color:white;font-family:system-ui,-apple-system,Segoe UI,sans-serif}.lgCard{width:min(430px,100%);background:linear-gradient(#102b47,#071827);border:1px solid #36536b;border-radius:22px;padding:22px;box-shadow:0 24px 80px #000b}.lgBrand{text-align:center;margin-bottom:18px}.lgBrand b{font-size:34px;color:#ffbd19}.lgBrand small{display:block;letter-spacing:.28em;font-weight:900}.lgCard h2{margin:8px 0}.lgCard p{color:#9eb0bf}.lgCard input{width:100%;box-sizing:border-box;background:#061522;border:1px solid #355570;border-radius:11px;color:#fff;padding:12px;margin:6px 0}.lgBtn{width:100%;border:0;border-radius:11px;padding:12px;margin:6px 0;background:#ffbd19;color:#07111d;font-weight:950}.lgGhost{background:#0a2035;color:#fff;border:1px solid #355570}.lgErr{color:#ff8c8c;min-height:18px;font-size:12px}.liveDot{display:inline-block;width:7px;height:7px;border-radius:50%;background:#62d56c;margin-right:5px}.liveAccount{border-color:#3a6a86!important}.liveAccount b{color:#ffbd19}.liveRole{text-transform:uppercase;font-size:9px;border:1px solid #a47a00;border-radius:99px;padding:4px 7px;color:#ffbd19}`;document.head.appendChild(s)}
function gate(html){let g=$('#liveGate');if(!g){g=document.createElement('div');g.id='liveGate';document.body.appendChild(g)}g.innerHTML=`<div class="lgCard">${html}</div>`;g.style.display='grid'}
function hideGate(){const g=$('#liveGate');if(g)g.style.display='none'}
function authView(msg=''){gate(`<div class="lgBrand"><small>MERRIMACK</small><b>Brewers</b></div><h2>Team Sign In</h2><p>This is now the live shared Brewers app.</p><input id="lgName" placeholder="Full name (for new accounts)"><input id="lgEmail" type="email" placeholder="Email"><input id="lgPass" type="password" placeholder="Password (6+ characters)"><div class="lgErr">${esc2(msg)}</div><button class="lgBtn" id="lgSignIn">SIGN IN</button><button class="lgBtn lgGhost" id="lgSignUp">CREATE ACCOUNT</button>`);$('#lgSignIn').onclick=signIn;$('#lgSignUp').onclick=signUp}
async function signIn(){const email=$('#lgEmail').value.trim(),password=$('#lgPass').value;const {error}=await sb.auth.signInWithPassword({email,password});if(error)return authView(error.message);await bootUser()}
async function signUp(){const full_name=$('#lgName').value.trim(),email=$('#lgEmail').value.trim(),password=$('#lgPass').value;if(!full_name)return authView('Enter your full name.');const {data,error}=await sb.auth.signUp({email,password,options:{data:{full_name}}});if(error)return authView(error.message);if(!data.session)return authView('Account created. Check your email to confirm it, then sign in.');await bootUser()}
function joinView(msg=''){gate(`<div class="lgBrand"><small>MERRIMACK</small><b>Brewers</b></div><h2>Join the Team</h2><p>Enter the private team code. The first account to join becomes the manager account.</p><input id="joinCode" value="BREWERS21" autocomplete="off"><div class="lgErr">${esc2(msg)}</div><button class="lgBtn" id="joinBtn">JOIN BREWERS</button><button class="lgBtn lgGhost" id="logoutBtn">SIGN OUT</button>`);$('#joinBtn').onclick=joinTeam;$('#logoutBtn').onclick=()=>sb.auth.signOut()}
async function joinTeam(){const code=$('#joinCode').value.trim();const {error}=await sb.rpc('join_team_with_code',{team_code:code});if(error)return joinView(error.message);await bootUser()}
async function bootUser(){const {data:{user:u}}=await sb.auth.getUser();user=u;if(!user)return authView();const {data:m,error}=await sb.from('team_members').select('team_id,role,is_active').eq('team_id',TEAM_ID).eq('user_id',user.id).maybeSingle();if(error||!m)return joinView(error?.message||'');membership=m;hideGate();await loadLive();decorateMore()}
function fixRoster(){try{for(let i=roster.length-1;i>=0;i--){if(['Steve Crow','Nolan Haberer'].includes(roster[i][1]))roster.splice(i,1)}const rsub=$('#roster .sub');if(rsub)rsub.textContent='2026 Merrimack Brewers · 25 players';document.querySelectorAll('.leaders .leader').forEach(el=>{if(/Nolan Haberer|Steve Crow/.test(el.textContent))el.remove()});document.querySelectorAll('#stats .stat').forEach(el=>{if(/HABERER|CROW/.test(el.textContent))el.remove()});if(typeof renderRoster==='function')renderRoster();if(typeof renderBat==='function')renderBat()}catch(e){console.warn(e)}}
async function loadLive(){fixRoster();const {data:g}=await sb.from('games').select('*').eq('team_id',TEAM_ID).gte('starts_at',new Date().toISOString()).order('starts_at').limit(1).maybeSingle();liveGame=g||null;await Promise.all([loadChat(),loadRsvp(),loadAnnouncement()]);subscribe();updateLabels()}
function updateLabels(){const cs=$('#chat .sub');if(cs)cs.innerHTML='<span class="liveDot"></span>LIVE TEAM CHAT · shared across devices';const ss=$('#schedule .sub');if(ss)ss.innerHTML='<span class="liveDot"></span>LIVE SCHEDULE + RSVP';const ns=$('#notifications .sub');if(ns)ns.innerHTML='<span class="liveDot"></span>LIVE ALERT CENTER'}
async function loadChat(){const {data:rows,error}=await sb.from('chat_messages').select('id,user_id,body,created_at').eq('team_id',TEAM_ID).eq('channel','team').order('created_at',{ascending:true}).limit(100);if(error)return;const ids=[...new Set((rows||[]).map(x=>x.user_id))];let names={};if(ids.length){const {data:p}=await sb.from('profiles').select('id,full_name').in('id',ids);(p||[]).forEach(x=>names[x.id]=x.full_name||'Brewer')}const box=$('#msgs');if(!box)return;box.innerHTML=(rows||[]).map(m=>`<div class="msg"><div class="av">${esc2((names[m.user_id]||'B').split(' ').map(x=>x[0]).slice(0,2).join(''))}</div><div><div class="mh"><b>${esc2(names[m.user_id]||'Brewer')}</b><span>${new Date(m.created_at).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}</span></div><div class="bubble">${esc2(m.body)}</div></div></div>`).join('')||'<div class="sub">No messages yet. Start the team chat.</div>'}
async function liveSend(){const input=$('#ci');const body=input?.value.trim();if(!body||!user)return;const {error}=await sb.from('chat_messages').insert({team_id:TEAM_ID,user_id:user.id,channel:'team',body});if(error){alert(error.message);return}input.value='';await loadChat()}
async function loadRsvp(){if(!liveGame||!user)return;const [{data:mine},{data:all}]=await Promise.all([sb.from('rsvps').select('status').eq('game_id',liveGame.id).eq('user_id',user.id).maybeSingle(),sb.from('rsvps').select('status').eq('game_id',liveGame.id)]);const c={going:0,maybe:0,out:0};(all||[]).forEach(x=>c[x.status]++);if(window.st){st.rsvp=mine?.status||'none';st.going=c.going;st.maybe=c.maybe;st.out=c.out;st.none=Math.max(0,25-c.going-c.maybe-c.out);st.game.opp=liveGame.opponent_name;const d=new Date(liveGame.starts_at);st.game.date=d.toLocaleDateString([],{weekday:'short',month:'short',day:'numeric',year:'numeric'});st.game.time=d.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'});st.game.field=[liveGame.venue_name,liveGame.venue_address].filter(Boolean).join(' · ');if(typeof game==='function'){game('gameHome');game('gameSched')}}}
async function liveRsvp(status){if(!user||!liveGame)return;if(status==='none'){await sb.from('rsvps').delete().eq('game_id',liveGame.id).eq('user_id',user.id)}else{const {error}=await sb.from('rsvps').upsert({game_id:liveGame.id,user_id:user.id,status,updated_at:new Date().toISOString()},{onConflict:'game_id,user_id'});if(error)return alert(error.message)}await loadRsvp()}
async function loadAnnouncement(){const {data:a}=await sb.from('announcements').select('title,body').eq('team_id',TEAM_ID).order('created_at',{ascending:false}).limit(1).maybeSingle();if(!a)return;if($('#annHome'))$('#annHome').textContent=a.body;if($('#pin'))$('#pin').innerHTML='📌 <b>'+esc2(a.title)+':</b> '+esc2(a.body)}
function subscribe(){if(window.__brewersLive)return;window.__brewersLive=true;sb.channel('brewers-live').on('postgres_changes',{event:'*',schema:'public',table:'chat_messages',filter:`team_id=eq.${TEAM_ID}`},loadChat).on('postgres_changes',{event:'*',schema:'public',table:'rsvps'},loadRsvp).on('postgres_changes',{event:'*',schema:'public',table:'games',filter:`team_id=eq.${TEAM_ID}`},loadLive).on('postgres_changes',{event:'*',schema:'public',table:'announcements',filter:`team_id=eq.${TEAM_ID}`},loadAnnouncement).subscribe()}
function decorateMore(){const more=$('#more');if(!more||$('#liveAccount'))return;const card=document.createElement('div');card.id='liveAccount';card.className='card liveAccount';card.innerHTML=`<div class="row"><b>LIVE ACCOUNT</b><span class="liveRole">${esc2(membership.role)}</span></div><div class="sub" style="margin:7px 0">${esc2(user.email||'Signed in')}</div><button class="btn ghost" id="claimMe">⚾ Claim my roster profile</button><button class="btn ghost" id="liveLogout">Sign out</button>`;more.insertBefore(card,more.children[2]||null);$('#liveLogout').onclick=()=>sb.auth.signOut();$('#claimMe').onclick=claimProfile}
async function claimProfile(){const {data:p}=await sb.from('profiles').select('full_name').eq('id',user.id).single();const name=(p?.full_name||'').trim();if(!name)return alert('Add your full name to your account first.');const {data:pl}=await sb.from('players').select('id,full_name,user_id').eq('team_id',TEAM_ID).ilike('full_name',name).maybeSingle();if(!pl)return alert(`I could not match “${name}” to the roster. A manager can link it manually.`);if(pl.user_id===user.id)return alert('Your roster profile is already linked.');if(pl.user_id)return alert('That roster profile is already claimed.');const {error}=await sb.from('player_claims').upsert({player_id:pl.id,user_id:user.id,status:'pending'},{onConflict:'player_id,user_id'});if(error)return alert(error.message);alert(membership.role==='manager'?'Claim request created. Manager approval is the next step.':'Claim request sent to a manager for approval.')}
function wire(){fixRoster();window.send=liveSend;window.rsvp=liveRsvp;const btn=$('.send');if(btn)btn.onclick=liveSend;const input=$('#ci');if(input)input.onkeydown=e=>{if(e.key==='Enter')liveSend()}}
async function start(){injectCss();fixRoster();const script=document.createElement('script');script.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';script.onload=async()=>{sb=window.supabase.createClient(SB_URL,SB_KEY);wire();sb.auth.onAuthStateChange((_e,s)=>setTimeout(()=>s?.user?bootUser():authView(),0));const {data:{session}}=await sb.auth.getSession();session?.user?await bootUser():authView()};script.onerror=()=>gate('<h2>Connection error</h2><p>Could not load the live database client. Refresh and try again.</p>');document.head.appendChild(script)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();