import {strict as assert} from 'node:assert';
import {readFile} from 'node:fs/promises';
import vm from 'node:vm';
import {resolve} from 'node:path';
let source=await readFile(new URL('../../scripts/espn-sync.mjs',import.meta.url),'utf8');
source=source.replace(/^import .*;\n/gm,'');
source=source.slice(0,source.lastIndexOf('main().catch('))+'\nvar testAPI={normalizePlayer,normalizeTeam,applyMatchupTotal};';
const sandbox={resolve,process:{cwd:()=>'.',env:{ESPN_S2:'fixture-only',ESPN_SWID:'fixture-only'},exit(){throw new Error('Unexpected exit')}},console};
vm.runInNewContext(source,sandbox);
const api=sandbox.testAPI;
const entry={playerId:12,lineupSlotId:0,appliedStatTotal:26.2,playerPoolEntry:{id:12,appliedStatTotal:26.2,player:{id:12,fullName:'Test Player',defaultPositionId:1,proTeamId:17,stats:[{scoringPeriodId:4,statSourceId:0,appliedTotal:26.2,stats:{3:269}}]}}};
assert.equal(api.normalizePlayer(entry,0,5,{}).points,0,'Unscoped previous-period points are ignored');
const current={...entry,appliedStatTotal:18.3,playerPoolEntry:{...entry.playerPoolEntry,player:{...entry.playerPoolEntry.player,stats:[{scoringPeriodId:5,statSourceId:0,appliedTotal:-2,stats:{3:0,4:0,19:1}}]}}};
const player=api.normalizePlayer(entry,0,5,{},current);
assert.equal(player.points,-2,'Current-period stat rows override the previous-period roster value');
assert.equal(player.scoringPeriodId,5);
assert.ok(player.gameStats.some(s=>s.id==='3'&&s.value===0),'A reported zero is retained');
const team=api.normalizeTeam({id:1,name:'Team',roster:{entries:[entry]}},5,{}, {rosterForCurrentScoringPeriod:{entries:[current]}});
assert.equal(team.starters[0].points,-2);
api.applyMatchupTotal(team,{totalPoints:0});assert.equal(team.total,0,'A reported zero matchup total overrides leftover roster points');
api.applyMatchupTotal(team,{totalPoints:-2.4});assert.equal(team.total,-2.4,'Provider corrections remain authoritative');
console.log('Passed: ESPN scoring-period isolation, weekly lineup stats, reported zeros, negative player points, and corrected provider totals.');
