import {strict as assert} from 'node:assert';
import {readFile} from 'node:fs/promises';
import vm from 'node:vm';
const player={player_id:'123',full_name:'Drake Maye',team:'NE',position:'QB',actual:26.2,projected:22,fantasyTeamName:'Purple team'};
const model={player,league:{week:5,teams:[]},ui:{league:'sleeper',playerTab:'stats',flaggedPlayers:{}}};
const intel={week:5,source_count:30,sources:[{id:'nfl',name:'NFL.com',url:'https://www.nfl.com',status:'available',matched_count:1}],players:{'drakemaye:NE':{reports:[{source:'NFL.com',week:5,status:'Questionable',practice:'Limited Participation',url:'https://www.nfl.com/injuries'}],news:[{source:'nfl',source_name:'NFL.com',title:'Drake Maye returns to practice',url:'https://www.nfl.com/news',published_at:'2026-10-06T15:00:00Z'}]}}};
const source=(source,value,week=5)=>({source,label:source,value,week,season:2026,scoring:'PPR'});
const consensus={week:5,players:{123:{sources:[source('one',10),source('two',30),source('stale',99,4),source('missing',null)]}}};
const commands=[],listeners={};const app={getUI:()=>model.ui,model:()=>model,render(){},dispatch:p=>commands.push(p),escape:v=>String(v??'').replaceAll('<','&lt;').replaceAll('"','&quot;'),format:(v,d=1,empty='—')=>v==null?empty:Number(v).toFixed(d),data:{actual:p=>p.actual,stats:()=>[{label:'Passing yards',value:269},{label:'STAT 999',value:20},{label:'PROJ Rushing touchdowns',value:.2,projected:true}]},markup:{face:()=>'<span></span>',gameLabel:()=> 'NE vs BUF'}};
const context={window:{FantasyCenter:app},document:{body:{dataset:{screen:'touch',root:'../patriots-fantasy-touch/'}},addEventListener:(name,fn)=>listeners[name]=fn},fetch:async url=>({ok:true,json:async()=>url.includes('player-intel')?intel:consensus}),URL,Date,Set,console};
vm.runInNewContext(await readFile(new URL('../player-details.js',import.meta.url),'utf8'),context);
const detail=context.window.FantasyPlayerDetails;
assert.ok(detail.render(model).includes('<b>269</b><small>Passing yards'));
assert.ok(!detail.render(model).includes('Rushing touchdowns'),'Projected statistics do not appear as actual game stats');
assert.ok(!detail.render(model).includes('STAT 999'),'Unidentified provider IDs are not presented as explained player statistics');
await new Promise(resolve=>setImmediate(resolve));
model.ui.playerTab='news';let html=detail.render(model);
assert.ok(html.includes('Questionable') && html.includes('Limited Participation'));
assert.ok(html.includes('Not published') && !html.includes('50%'),'Questionable does not invent a playing probability');
assert.ok(html.includes('Drake Maye returns to practice') && html.includes('1 / 30 news sources accessible'));
assert.equal(detail.injurySummary(player).practice,'Limited Participation');
assert.equal(detail.injurySummary(player).week,5,'Summary panels retain the injury report week independently of the stats week');
model.ui.playerTab='projections';html=detail.render(model);
assert.ok(html.includes('20.0') && html.includes('2 contributing sources'));
listeners.click({target:{closest:()=>({dataset:{flagPlayer:'sleeper:123',detailPlayer:'123',detailTab:'news'}})}});
assert.equal(commands[0].playerFlag['sleeper:123'],true);
assert.equal(commands[0].playerId,'123','Flag commands retain their player context');
assert.equal(commands[0].playerTab,'news','Flag commands retain the displayed tab');
listeners.click({target:{closest:()=>({dataset:{playerTab:'news',detailPlayer:'123'}})}});
assert.equal(commands[1].playerTab,'news');
assert.equal(commands[1].playerId,'123','News tab commands select the intended player atomically');
assert.ok(!html.includes('99.0'),'A stale week is excluded from the average');
context.window.FantasyProjectionCloud={get:(p,c)=>c.week===5?{calculated_average:24,sources_counted:3,updated_at:'2026-10-08T01:38:26Z'}:null};
player.consensus={cloud:true};player.providerProjected=22;player.projected=24;
html=detail.render(model);
assert.ok(html.includes('Sleeper projection') && html.includes('<b>22.0</b>'),'The provider label retains its own projection');
assert.ok(html.includes('Cloud average') && html.includes('<b>24.0</b>') && html.includes('3 contributing sources'),'The existing panel displays the current cloud average and contributor count');
assert.ok(!html.includes('Source range 10.0'),'An older provider range is not attributed to the cloud average');
assert.equal(detail.average(player,4).value,null,'A cloud batch from another week is not displayed');
const projectedLabels=['Passing yards','Passing touchdowns','Interceptions','Completions','Passing attempts','Rushing yards','Rushing attempts','Rushing touchdowns','Fumbles','Fumbles lost','Rushing first downs','Sacks taken','Receptions','Receiving yards','Receiving touchdowns','Targets','Field goals','Extra points','Sacks','Tackles','Defensive interceptions','Defensive touchdowns'];
const tvApp={...app,data:{...app.data,stats:()=>projectedLabels.map((label,i)=>({label:'PROJ '+label,value:i+.1,projected:true}))}};
const tvContext={...context,window:{FantasyCenter:tvApp,FantasyProjectionCloud:context.window.FantasyProjectionCloud},document:{body:{dataset:{screen:'tv',root:'../patriots-fantasy-touch/'}},addEventListener(){}}};
vm.runInNewContext(await readFile(new URL('../player-details.js',import.meta.url),'utf8'),tvContext);
const tvDetail=tvContext.window.FantasyPlayerDetails;
model.ui.playerTab='projections';const wide=tvDetail.render(model,true);
for(const label of projectedLabels)assert.ok(wide.includes('<small>'+label+'</small>'),'Every reported projection is retained, including '+label);
assert.ok(wide.includes('Sleeper projection') && wide.includes('<b>22.0</b>') && wide.includes('Cloud average') && wide.includes('<b>24.0</b>'),'Both independently sourced projection totals remain visible');
assert.ok(wide.includes('3 contributing sources') && wide.includes('data-node-key="sleeper:123"'));
assert.ok(!wide.includes('detail-stats-scroll'),'The TV projection view does not put its stat breakdown in a scroll drawer');
assert.ok(html.includes('detail-stats-scroll'),'The touch controller retains its normal player drawer');
await new Promise(resolve=>setImmediate(resolve));model.ui.playerTab='news';const wideNews=tvDetail.render(model,true);
assert.ok(wideNews.includes('Questionable') && wideNews.includes('Limited Participation') && wideNews.includes('Drake Maye returns to practice'));
console.log('Passed: original stats, player flags, synced tabs, practice reports, news source counts, honest probability, same-week means, accurate cloud/provider projection labels, and complete TV projection grids.');
