import {strict as assert} from 'node:assert';
import {readFile} from 'node:fs/promises';
import vm from 'node:vm';
const elements=new Map();
const element=id=>{if(!elements.has(id))elements.set(id,{innerHTML:'',textContent:'',dataset:{},hidden:false,offsetWidth:80,classList:{add(){},remove(){},toggle(){}},addEventListener(){},querySelector(){return null}});return elements.get(id)};
const player=(id,starter)=>({player_id:id,full_name:'Player '+id,position:'WR',team:'NE',starter,status:'FINAL',actual:id==='own-0'?0:2,projected:3,fantasyTeamColor:'#f47b35'});
const own=Array.from({length:18},(_,i)=>player('own-'+i,i<9)), opponent=Array.from({length:20},(_,i)=>player('opp-'+i,i<10));
const teams=[{id:'1',name:'Own',teamColor:'#f47b35',total:18,players:own},{id:'2',name:'Other',teamColor:'#aca0e5',total:20,players:opponent}];
const matchups=Array.from({length:6},(_,i)=>({id:String(i),home:teams[0],away:teams[1],homeScore:0,awayScore:2}));
const model={loading:false,started:true,leagueStarted:true,ui:{league:'sleeper',view:'overview',playerId:null},ownActual:18,opponentActual:20,ownFinish:18,opponentFinish:20,history:[],teamHistory:[],events:[],matchups,league:{ready:true,week:4,ownName:'Own',opponentName:'Other',own,opponent,teams,allPlayers:own.concat(opponent)}};
const document={body:{dataset:{screen:'tv'}},documentElement:{style:{setProperty(){}}},getElementById:element,querySelectorAll:()=>[],querySelector:()=>null,addEventListener(){},activeElement:null};
const app={model:()=>model,getUI:()=>model.ui,render(){context.window.FantasyGlass?.render()},format:(v,d=1,empty='—')=>v==null?empty:Number(v).toFixed(d),escape:v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;'),data:{actual:p=>p.actual,record:()=> '3–1'},markup:{face:()=>'<span class="player-face"></span>',stats:()=>'<div>269 passing yards</div>',gameLabel:()=>''},dispatch(){}};
const context={window:{FantasyCenter:app,innerHeight:720,innerWidth:1280,addEventListener(){}},document,CSS:{escape:v=>v},Date,Map,Set,URL};
vm.runInNewContext(await readFile(new URL('../soft-glass.js',import.meta.url),'utf8'),context);
vm.runInNewContext(await readFile(new URL('../tv-presentation.js',import.meta.url),'utf8'),context);
const tv=context.window.FantasyTV, html=element('workspace').innerHTML;
assert.equal((html.match(/data-tv-player=/g)||[]).length,38,'TV includes every starter and reserve from both complete teams');
assert.equal((html.match(/tv-starter-row/g)||[]).length,19);
assert.equal((html.match(/tv-bench-row/g)||[]).length,19);
assert.ok(html.includes('own-0')&&html.includes('<b>0.0</b>'),'Reported zero player scores remain zero');
assert.equal((tv.matchups(model).match(/class="tv-matchup"/g)||[]).length,2,'Short TV screens bound the secondary matchup count');
assert.equal((tv.matchups(model,true).match(/class="tv-matchup"/g)||[]).length,6,'League scene retains all matchups');
const seen=[0,15000,30000].flatMap(at=>Array.from(tv.page(matchups,2,at).items,r=>r.id));
assert.equal(new Set(seen).size,6,'Rotating pages expose every league matchup');
context.window.innerHeight=1080;
assert.equal((tv.matchups(model).match(/class="tv-matchup"/g)||[]).length,3);
model.ui.playerId='opp-0';model.player=opponent[0];app.render();
assert.ok(element('workspace').innerHTML.includes('tv-player-detail'),'Controller player selection retains the full TV stats scene');
model.ui.playerId=null;model.ui.view='league';app.render();
assert.ok(element('workspace').innerHTML.includes('tv-league-full'));
const records=[{at:'2026-10-04T17:00:00Z',values:[10,12]},{at:'2026-10-04T17:01:00Z',values:[8,13]}];
const chart=context.window.FantasyGlassCharts.chart([{value:8,color:'#f47b35'},{value:13,color:'#aca0e5'}],records,{timeline:true});
assert.ok(chart.includes('2 updates'),'An unchanged display tail does not invent score updates');
assert.equal((tv.fantasyStrip(model).match(/class="tv-strip-matchup"/g)||[]).length,3,'Fantasy ribbon shows three complete matchups');
model.leagueStarted=false;
assert.ok(tv.fantasyStrip(model).includes('18.0'),'Upcoming fantasy scores use actual team totals, not projected matchup scores');
model.leagueStarted=true;
const nfl=(id,state,score)=>({id,date:'2026-10-08T00:15:00Z',status:{type:{state,shortDetail:state==='in'?'Q2 5:12':'Scheduled'}},competitions:[{competitors:[{homeAway:'away',score,team:{abbreviation:'NE',logo:'https://a.espncdn.com/NE.png'}},{homeAway:'home',score:7,team:{abbreviation:'BUF',logo:'https://a.espncdn.com/BUF.png'}}]}]});
model.games=[nfl('old','post',99)];model.nflWeek=5;model.nflGames=Array.from({length:10},(_,i)=>nfl(String(i),i===0?'in':'pre',0));
const nflHtml=tv.nflStrip(model);
assert.equal((nflHtml.match(/class="tv-nfl-game/g)||[]).length,6);
assert.ok(nflHtml.includes('Week 5') && nflHtml.includes('Q2 5:12') && nflHtml.includes('<strong>0</strong>'),'Live zero is an actual score');
assert.ok(nflHtml.includes('<strong>—</strong>') && !nflHtml.includes('<strong>99</strong>'),'Upcoming scores are blank and old fantasy-week games do not leak into the current NFL ribbon');
context.window.FantasyPlayerDetails={fetchData(){},injurySummary:p=>({status:p.player_id==='own-0'?'Questionable':null,practice:null,source:'CBS Sports',date:'Oct 5',week:5})};
assert.ok(tv.injuries(model).includes('Practice not reported') && tv.injuries(model).includes('CBS Sports · W5 · Oct 5'),'Injury panel identifies report week and date without inventing a practice result');
const upcoming={...own[0],status:'NEXT',injury_status:'Questionable',event:{date:'2026-10-11T13:30:00Z',competitions:[{status:{type:{state:'pre'}},competitors:[{team:{abbreviation:'NE'},homeAway:'away'},{team:{abbreviation:'PHI'},homeAway:'home'}]}]}};
const playerRow=tv.row(upcoming,false,model);
assert.ok(playerRow.includes('Sun 9:30 AM @ PHI'),'Every row has an Eastern kickoff time and opponent');
assert.ok(playerRow.includes('tv-injury-badge') && playerRow.includes('Injury: Questionable'),'Questionable players carry an accessible injury marker');
assert.ok(playerRow.includes('tv-player-projection') && playerRow.includes('--team-color:#f47b35'),'Projection values use the same fantasy-team color as the stock chart');
assert.ok(tv.row(upcoming,true,model).includes('tv-player-projection'),'Reserve players also retain projections and game times');
upcoming.event.competitions[0].status.type={state:'in',shortDetail:'Q2 5:12'};
assert.ok(tv.row(upcoming,false,model).includes('LIVE · Q2 5:12'),'Live game progress replaces the pregame time');
assert.equal(tv.injuryInfo({...upcoming,injury_status:'ACTIVE'}),null,'Active players are not flagged as injured');
assert.equal(tv.injuryInfo({...upcoming,injury_status:'INJURY_RESERVE'}).label,'IR');
assert.equal(tv.gameInfo({team:'CAR',status:'NO GAME'},{league:{week:5},games:Array(14).fill({})}).phase,'bye','A complete weekly slate distinguishes a bye from a missing feed');
console.log('Passed: complete TV rosters, rotating matchups and reserves, current-week isolation, colored projections, kickoff/live labels, yellow injury markers, player scenes, and retained chart corrections.');
